name: Get Link

on:
  push:
    branches:
      - main  # Triển khai khi có code được push lên nhánh 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'  # Sử dụng phiên bản PHP tương ứng
        extensions: mbstring, intl, bcmath
        ini-values: post_max_size=256M, max_execution_time=300
        coverage: none

    - name: Install Composer dependencies
      run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader --no-dev

    - name: Prepare Laravel environment
      run: |
        cp .env.example .env
        php artisan key:generate

    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_IP }}
        username: ${{ secrets.HOST_USERNAME }}
        key: ${{ secrets.HOST_SSH_KEY }}
        script: |
          cd /public_html  
          git pull origin main
          composer install --no-dev
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          php artisan storage:link
          chown -R www-data:www-data /public_html  
