name: Deploy via FTP

on:
  push:
    branches:
      - main  # Triển khai khi có code được push lên nhánh 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'  # Sử dụng phiên bản PHP tương ứng
        extensions: mbstring, intl, bcmath
        ini-values: post_max_size=256M, max_execution_time=300
        coverage: none

    - name: Install Composer dependencies
      run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader --no-dev

    - name: Prepare Laravel environment
      run: |
        cp .env.example .env
        php artisan key:generate

    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local_dir: ./home/editorvn   # Thư mục chứa mã nguồn của bạn
        server_dir: /public_html   # Thư mục trên server FTP nơi bạn muốn deploy
        git_ftp: true
        dry_run: false  # Đặt là true nếu bạn muốn thử nghiệm trước khi thực hiện

    - name: Run post-deploy commands
      run: |
        sshpass -p "${{ secrets.FTP_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${FTP_USERNAME}@${FTP_SERVER} << 'EOF'
          chown -R www-data:www-data /public_html
        EOF
